export const skills = [
  { label: 'Languages', items: ['Python', 'JavaScript', 'C++', 'SQL', 'HTML', 'CSS'] },
  { label: 'Frameworks & Web', items: ['React', 'Next.js', 'Node.js', 'Flask', 'FastAPI', 'LangChain'] },
  { label: 'AI & Machine Learning', items: ['Llama 3', 'GPT-4', 'OpenAI API', 'Groq API', 'TensorFlow', 'Scikit-Learn', 'OpenCV', 'NLTK', 'SpaCy'] },
  { label: 'Databases', items: ['MongoDB', 'MySQL', 'Supabase'] },
  { label: 'Tools & Workflow', items: ['Git', 'GitHub', 'Figma', 'VS Code', 'XAMPP'] },
];
export const softSkills = [
  ['Problem solving', 'Turned traffic congestion and manual quiz creation into working systems.'],
  ['Ownership', 'Built whole products, from interface and model to deployment.'],
  ['Communication & user focus', 'Designed AI dashboards for educators and students.'],
  ['Adaptability', 'Applied LLMs, computer vision, NLP and voice AI.'],
  ['Collaboration', 'Delivered a production-style feature at Digital Scrap.'],
];
export const projects = [
  { name: 'EduQuizAI', category: 'FULL-STACK · GENERATIVE AI', summary: 'Lecture notes in. Quizzes, assignments and summaries out. An AI platform built for educators and students.', stack: ['React', 'Next.js', 'FastAPI', 'Llama 3.3 70B', 'LangChain', 'Supabase', 'Groq API', 'Python', 'FPDF'], visual: 'quiz', situation: 'Educators spend hours manually creating quizzes, assignments and summaries from lecture material.', task: 'Automate content creation from uploaded notes in common formats, with a simple educator–student experience.', action: 'Integrated **Llama 3.3 70B** through Groq. Built a **PDF, DOCX, PPT and TXT** pipeline, a React/Next.js dashboard, authentication, storage and automated PDF generation.', result: 'Reduced manual content-creation effort by **up to 80%**, with seamless educator–student content delivery.' },
  { name: 'SmartTraffic', category: 'COMPUTER VISION · REAL-TIME SYSTEMS', summary: 'A traffic management system that sees road density and adapts signal timing in real time.', stack: ['Python', 'Flask', 'OpenCV', 'Haar Cascade', 'JavaScript', 'HTML', 'CSS', 'Multithreading'], visual: 'traffic', situation: 'Fixed-timer signals ignore actual traffic, creating congestion and relying on manual analysis.', task: 'Automate vehicle detection and optimize signal schedules from live traffic data.', action: 'Built vehicle detection with OpenCV and Haar Cascade, monitoring **4 directions** with **2 concurrent processing components** and a live Flask dashboard.', result: 'Detection at **~33 FPS**, with adaptive signal timing of **60–300 seconds** based on vehicle density and less manual traffic analysis.' },
  { name: 'Lateral Reading', category: 'NLP · MACHINE LEARNING', summary: 'A credibility analyzer that uses linguistic features to help flag unreliable text and information sources.', stack: ['Python', 'NLTK', 'SpaCy', 'Machine Learning'], visual: 'nlp', situation: 'Unreliable information spreads easily online and is difficult for readers to evaluate quickly.', task: 'Help identify unreliable text and sources using lateral-reading principles.', action: 'Implemented a **full NLP pipeline**: tokenization, preprocessing, feature extraction and classification. Refined linguistic features using SpaCy and NLTK.', result: 'A working text classifier with **improved classification reliability** through engineered linguistic features.' },
  { name: 'AI Voice Assistant', category: 'INTERNSHIP · DIGITAL SCRAP', summary: 'A real-time voice assistant that lets users talk naturally, with AI responses and secure access.', stack: ['React.js', 'Flask', 'Deepgram API', 'Firebase Authentication'], visual: 'voice', private: true, situation: 'Digital Scrap needed an interactive assistant that users could talk to instead of typing.', task: 'Deliver a full-stack assistant with accurate speech recognition and secure user access.', action: 'Built React.js and Flask interfaces for **real-time speech-to-text** and AI responses, with Deepgram transcription and Firebase Authentication.', result: '**Accurate voice recognition** and **secure session management**, delivered during a **3-month internship (Jul–Sep 2026)**.' },
];